CREATE TABLE Estado (
    ID int NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(255) NOT NULL, 
    PRIMARY KEY (ID)
);


CREATE TABLE Zombie (
    ID int NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(255) NOT NULL, 
    ID_estado INT REFERENCES Estado(ID) ON DELETE SET NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Registros(
    ID int NOT NULL AUTO_INCREMENT,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    ID_estado INT REFERENCES estado(ID) ON DELETE SET NULL,
    ID_zombie INT REFERENCES zombie(ID) ON DELETE SET NULL,
    PRIMARY KEY (ID)
);
